/**
 * Company names of current Nasdaq Stockholm Large Cap constituents,
 * captured 2026-09-08. Mid Cap and Small Cap tiers were also researched and
 * are still exported individually below in case broader coverage is wanted
 * later, but are deliberately excluded from SWEDISH_INDEX_NAMES — product
 * decision to scope Swedish index-membership filtering to large caps only,
 * unlike Germany's DAX+MDAX+SDAX breadth.
 *
 * UNLIKE every other index file in this project (germanIndices.ts,
 * austrianIndices.ts, spanishIndices.ts, belgianIndices.ts — all keyed by
 * ISIN), this one is keyed by plain company name, not ISIN. Reason: the
 * authoritative source for segment membership — Nasdaq's own Gross Index
 * "Weighting" exports (OMXSLCGI/OMXSMCGI/OMXSSCGI at
 * indexes.nasdaq.com/Index/ExportWeightings/..., not disallowed by
 * robots.txt) — only exposes Company Name + Symbol; ISIN requires a paid/
 * registered login. The underlying API that does carry ISIN
 * (api.nasdaq.com) has `robots.txt: Disallow: /` for all crawlers and was
 * correctly not used. Per-company detail pages on nasdaq.com do show ISIN
 * but that host sets `Crawl-delay: 30`, making a per-company fetch for ~395
 * companies impractical for a single research pass (3+ hours). Only 2 of
 * 395 ISINs were independently spot-verified (Volvo B: SE0000115446,
 * Investor B: SE0000107419) via Wikipedia/Deutsche Börse/extraETF — not
 * enough to build a usable ISIN Set.
 *
 * A caller matching this against scripts/lib/parseFi.ts's `issuerName`
 * field (Finansinspektionen's Insynsregistret data, which does carry ISIN
 * itself) will need fuzzy/normalized name matching — legal-suffix and
 * casing conventions won't line up exactly between this Nasdaq export and
 * FI's own issuer-name strings — same caveat as DUTCH_INDEX_NAMES in
 * dutchIndices.ts. Multiple share classes of the same company (e.g. "Volvo,
 * AB ser. A" / "ser. B") are kept as separate entries here, matching the
 * source's per-instrument listing rather than per-company.
 *
 * Segment counts: Large Cap 161, Mid Cap 131, Small Cap 105 (397 total) —
 * matches Nasdaq's own overview-page counts exactly.
 *
 * Segments are reviewed periodically by Nasdaq — refresh this list against
 * the same indexes.nasdaq.com export URLs so it doesn't silently drift out
 * of date. To get proper ISIN coverage in the future, a paid reference-data
 * source (Nasdaq GIDS, a market-data vendor, or ESMA's free FIRDS bulk
 * register filtered to MIC XSTO) would be needed rather than scraping.
 */
const OMX_LARGE_CAP_NAMES = [
  "TRATON SE",
  "AAK AB",
  "ABB Ltd",
  "Addtech AB ser. B",
  "AFRY AB",
  "Alfa Laval AB",
  "AddLife AB ser. B",
  "Alimak Group AB",
  "Autoliv Inc. SDB",
  "Alleima AB",
  "Altra Fastigheter AB",
  "Alvotech SDB",
  "Addnode Group AB ser. B",
  "AQ Group AB",
  "Arion Banki hf SDB",
  "Asker Healthcare Group AB",
  "ASMODEE GROUP AB",
  "ASSA ABLOY AB ser. B",
  "Atlas Copco AB ser. A",
  "Atlas Copco AB ser. B",
  "Atrium Ljungberg AB ser. B",
  "Axfood AB",
  "Avanza AB",
  "AstraZeneca PLC",
  "Fastighets AB Balder ser. B",
  "Beijer Alma AB ser. B",
  "Beijer Ref AB ser. B",
  "Betsson AB ser. B",
  "Bilia AB ser. A",
  "Billerud Aktiebolag",
  "BioArctic AB ser. B",
  "Boliden AB",
  "BONESUPPORT HOLDING AB",
  "Bravida Holding AB",
  "Bufab AB",
  "Bure Equity AB",
  "CAMURUS AB",
  "Castellum AB",
  "Catena AB",
  "Clas Ohlson AB ser. B",
  "Corem Property Group AB ser. A",
  "Corem Property Group AB ser. B",
  "Corem Property Group AB ser. D",
  "DOMETIC GROUP AB",
  "Elekta AB ser. B",
  "Electrolux AB ser. A",
  "Electrolux AB ser. B",
  "Embracer Group AB ser. B",
  "engcon AB ser. B",
  "Epiroc AB ser. A",
  "Epiroc AB ser. B",
  "Electrolux Professional AB ser. B",
  "EQT AB",
  "Ericsson (Telefonab. L M) ser. A",
  "Ericsson ser. B",
  "Essity AB ser. A",
  "Essity AB ser. B",
  "Evolution AB",
  "Fabege AB",
  "Fenix Outdoor International AG",
  "Fastpartner AB ser. A",
  "Fastpartner AB ser. D",
  "Getinge AB ser. B",
  "Granges AB",
  "Hacksaw AB",
  "Hemnet Group AB",
  "Hexagon AB ser. B",
  "Hennes & Mauritz AB (H&M) ser. B",
  "HMS Networks AB",
  "Holmen AB ser. A",
  "Holmen AB ser. B",
  "HEXPOL AB ser. B",
  "Hufvudstaden AB ser. A",
  "Husqvarna AB ser. A",
  "Husqvarna AB ser. B",
  "Indutrade AB",
  "Industrivarden AB ser. A",
  "Industrivarden AB ser. C",
  "Investor AB ser. A",
  "Investor AB ser. B",
  "International Petroleum Corporation",
  "INVISIO AB",
  "JM AB",
  "Kinnevik AB ser. A",
  "Kinnevik AB ser. B",
  "Lagercrantz Group AB ser. B",
  "Latour Investmentab. ser. B",
  "Lindab International AB",
  "Lifco AB ser. B",
  "Loomis AB",
  "Lundin Gold Inc.",
  "Lundin Mining Corporation",
  "Lundbergforetagen AB ser. B",
  "Medicover AB ser. B",
  "Mips AB",
  "Munters Group AB",
  "Mycronic AB",
  "NCC AB ser. A",
  "NCC AB ser. B",
  "Nordea Bank Abp",
  "New Wave Group AB ser. B",
  "NIBE Industrier AB ser. B",
  "NOBA Bank Group AB",
  "Nolato AB ser. B",
  "NP3 Fastigheter AB",
  "Octave Intelligence plc SDR",
  "OEM International AB ser. B",
  "Paradox Interactive AB",
  "Peab AB ser. B",
  "Pandox AB ser. B",
  "PPI Public Property Invest AB",
  "Roko AB",
  "SAAB AB ser. B",
  "Sagax AB ser. A",
  "Sagax AB ser. B",
  "Sagax AB ser. D",
  "Sampo OYJ",
  "Sandvik AB",
  "Nordnet AB",
  "Svenska Cellulosa AB SCA ser. A",
  "Svenska Cellulosa AB SCA ser. B",
  "Skand. Enskilda Banken ser. A",
  "Skand. Enskilda Banken ser. C",
  "SECTRA AB ser. B",
  "Securitas AB ser. B",
  "Svenska Handelsbanken ser. A",
  "Svenska Handelsbanken ser. B",
  "Scandic Hotels Group AB",
  "Sinch AB",
  "Skanska AB ser. B",
  "SKF AB ser. A",
  "SKF AB ser. B",
  "SkiStar AB ser. B",
  "Swedish Orphan Biovitrum AB",
  "SSAB AB ser. A",
  "SSAB AB ser. B",
  "Stora Enso Oyj ser. A",
  "Stora Enso Oyj ser. R",
  "Storskogen Group AB ser. B",
  "SWECO AB ser. A",
  "SWECO AB ser. B",
  "Swedbank AB ser. A",
  "Systemair AB",
  "Tele2 AB ser. A",
  "Tele2 AB ser. B",
  "Telia Company AB",
  "Thule Group AB",
  "Tieto Corporation",
  "Trelleborg AB ser. B",
  "Troax Group AB",
  "Truecaller AB ser. B",
  "Vimian Group AB",
  "Vitec Software Group AB ser. B",
  "Vitrolife AB",
  "Volvo Car AB ser. B",
  "Volvo AB ser. A",
  "Volvo AB ser. B", // SE0000115446, one of only 2 ISINs independently verified — see header
  "Verisure plc",
  "Wallenstam AB ser. B",
  "Wihlborgs Fastigheter AB",
  "Yubico AB",
];

export const OMX_MID_CAP_NAMES = [
  "AcadeMedia AB",
  "Acast AB",
  "Alligo AB ser. B",
  "Ambea AB",
  "Apotea AB",
  "Arjo AB ser. B",
  "Arctic Paper S.A.",
  "ATTENDO AB",
  "Avarda Bank AB",
  "Bergman & Beving AB ser. B",
  "Besqab AB",
  "Better Collective A/S",
  "BHG Group AB",
  "BICO Group AB",
  "BioInvent International AB",
  "BioGaia AB ser. B",
  "Byggmax Group AB",
  "Bonava AB ser. A",
  "Bonava AB ser. B",
  "Boozt AB",
  "Brinova Fastigheter AB ser. B",
  "BTS Group AB ser. B",
  "Catella AB ser. A",
  "Catella AB ser. B",
  "Cavotec Group AB",
  "CellaVision AB",
  "Cibus Real Estate AB",
  "Cloetta AB ser. B",
  "Coor Service Management Holding AB",
  "CTT Systems AB",
  "Cynca Nordic AB",
  "Dios AB",
  "DUNI",
  "Dustin Group AB",
  "Dynavox Group AB",
  "Eastnine AB",
  "Egetis Therapeutics AB",
  "Elanders AB ser. B",
  "Fastighetsbolaget Emilshus AB",
  "Enea AB",
  "Enity Holding AB",
  "Ependion AB",
  "Ework Group AB",
  "Fagerhult Group AB",
  "Fasadgruppen Group AB",
  "Flat Capital AB ser. B",
  "Flerie AB",
  "FM Mattsson AB ser. B",
  "Gentoo Media Inc.",
  "Genova Property Group AB",
  "Green Landscaping Group AB",
  "HANZA AB",
  "Heba Fastighets AB ser. B",
  "Hansa Biopharma AB",
  "Hoist Finance AB",
  "Hexatronic Group AB",
  "Humana AB",
  "Humble Group AB",
  "Instalco AB",
  "Intea Fastigheter AB ser. B",
  "Intea Fastigheter AB ser. D",
  "Intrum AB",
  "Inwido AB",
  "ITAB Group AB",
  "John Mattson Fastighetsforetagen",
  "KABE Group AB ser. B",
  "Karnov Group AB",
  "Karnell Group AB ser. B",
  "K-Fast Holding AB ser. B",
  "KlaraBo Sverige AB ser. B",
  "Know IT AB",
  "Lime Technologies AB",
  "Logistea AB ser. B",
  "MedCap AB",
  "MEKO AB",
  "Meren Energy Inc.",
  "MilDef Group AB",
  "Momentum Group AB ser. B",
  "Morrow Bank AB",
  "Modern Times Group MTG AB ser. A",
  "Modern Times Group MTG AB ser. B",
  "NCAB Group AB",
  "Nelly Group AB",
  "NEOBO FASTIGHETER AB",
  "Net Insight AB ser. B",
  "Nivika Fastigheter AB ser. B",
  "Nederman Holding AB",
  "Nobia AB",
  "Norion Bank AB",
  "NOTE AB",
  "Stockholm Nordtech Group AB",
  "Oresund Investmentab",
  "Orron Energy AB",
  "Ovzon AB",
  "Proact IT Group AB",
  "PowerCell Sweden AB",
  "Platzer Fastigheter Holding AB",
  "Prisma Properties AB",
  "Ratos AB ser. A",
  "Ratos AB ser. B",
  "RaySearch Laboratories AB ser. B",
  "Rejlers AB ser. B",
  "Rusta AB",
  "RVRC Holding AB",
  "SALIX GROUP AB",
  "Samhallsbyggnadsbolaget i Norden AB ser. B",
  "Samhallsbyggnadsbolaget i Norden AB ser. D",
  "Scandi Standard AB",
  "Sdiptech AB ser. B",
  "Stillfront Group AB",
  "Stenhus Fastigheter i Norden AB",
  "SILEX MICROSYSTEM AB",
  "Swedish Logistic Property AB ser. B",
  "SmartCraft Group AB",
  "Stendorren Fastigheter AB",
  "Storytel AB ser. B",
  "Sveafastigheter AB",
  "Svedbergs Group AB ser. B",
  "Synsam AB",
  "Tangen Industrikapital AB",
  "Traction AB ser. B",
  "Fastighets AB Trianon ser. B",
  "VBG GROUP AB ser. B",
  "Vicore Pharma Holding AB",
  "Gruvaktiebolaget Viscaria",
  "VNV Global AB",
  "Volati AB",
  "Viaplay Group AB ser. A",
  "Viaplay Group AB ser. B",
  "XANO Industri AB ser. B",
  "XVIVO PERFUSION AB",
];

export const OMX_SMALL_CAP_NAMES = [
  "Ascelia Pharma AB",
  "Acrinova AB ser. A",
  "Acrinova AB ser. B",
  "Active Biotech AB",
  "ANNEHEM FASTIGHETER AB",
  "Arla Plast AB",
  "Actic Group AB",
  "Alligator Bioscience AB",
  "B3 Consulting Group AB",
  "Bactiguard Holding AB ser. B",
  "Balco Group AB",
  "BE Group AB",
  "Berner Industrier AB ser. B",
  "Bong AB",
  "Bjorn Borg AB",
  "Boule Diagnostics AB",
  "Bulten AB",
  "Cantargia AB",
  "Carasent AB",
  "Cinclus Pharma Holding AB",
  "Concejo AB ser. B",
  "C-RAD AB ser. B",
  "CTEK AB",
  "Catena Media P.L.C",
  "Dedicare AB ser. B",
  "Duroc AB ser. B",
  "Enad Global 7 AB",
  "Ellos Holding AB",
  "Elon AB",
  "Eltel AB",
  "Eniro Group AB",
  "Eolus AB ser. B",
  "Episurf Medical AB ser. B",
  "EQL Pharma AB",
  "AB Fastator",
  "Ferronordic AB",
  "Fortinova Fastigheter AB ser. B",
  "G5 Entertainment AB",
  "Garo AB",
  "HAKI Safety AB ser. A",
  "HAKI Safety AB ser. B",
  "Infant Bacterial Therapeutics AB",
  "Immunovia AB",
  "Mendus AB",
  "Infrea AB",
  "Inission AB ser. B",
  "INQ Group AB",
  "IRLAB Therapeutics AB ser. A",
  "Image Systems AB",
  "Isofol Medical AB",
  "K2A Knaust & Andersson Fastigheter AB",
  "KDventures AB ser. B",
  "Keo Capital AB",
  "Lammhults Design Group ser. B",
  "Mangold AB",
  "Malmbergs Elektriska AB ser. B",
  "Moberg Pharma AB",
  "Moment Group AB",
  "Micro Systemation AB ser. B",
  "Midsona AB ser. A",
  "Midsona AB ser. B",
  "Medivir AB",
  "NAXS AB",
  "Netel Holding AB",
  "Nanologica AB",
  "Nordisk Bergteknik AB ser. B",
  "NOVOTEK AB ser. B",
  "Nyorda AB",
  "Oncopeptides AB",
  "Orexo AB",
  "Pierce Group AB",
  "PION Group AB ser. B",
  "Precise Biometrics AB",
  "Prevas AB ser. B",
  "Profoto Holding AB",
  "Pricer AB ser. B",
  "ProfilGruppen AB ser. B",
  "Q-Linea AB",
  "Qliro AB",
  "Railcare Group AB",
  "Rottneros AB",
  "mySafety Group AB ser. B",
  "Saniona AB",
  "Seafire AB",
  "Sedana Medical AB",
  "Senzime",
  "Solid Forsakringsaktiebolag",
  "Sensys Gatso Group AB",
  "SinterCast AB",
  "Sivers Semiconductors AB",
  "Sleep Cycle AB",
  "Softronic AB ser. B",
  "Starbreeze AB ser. A",
  "Starbreeze AB ser. B",
  "Stockwik AB",
  "Studsvik AB",
  "SynAct Pharma AB",
  "Tobii AB",
  "Transtema AB",
  "Vivesto AB",
  "Wastbygg Gruppen AB ser. B",
  "Wise Group AB",
  "Wall to Wall Group AB ser. A",
  "Xbrane Biopharma AB",
  "XSpray Pharma AB",
];

export const SWEDISH_INDEX_NAMES = new Set(OMX_LARGE_CAP_NAMES);
